apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 258452927903.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 258452927903.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: dd9936e2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
